package hibernate_beans;
// Generated 2017-4-28 5:44:07 by Hibernate Tools 5.2.1.Final

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * ClientAddress generated by hbm2java
 */
@Entity
@Table(name = "client_address")
public class ClientAddress implements java.io.Serializable {

	private ClientAddressId id;
	private Client client;
	private String recepteur;
	private String address;
	private String codePostal;
	private String ville;
	private String pays;
	private String telephone;

	public ClientAddress() {
	}

	public ClientAddress(ClientAddressId id, Client client, String recepteur, String address, String codePostal,
			String ville, String pays, String telephone) {
		this.id = id;
		this.client = client;
		this.recepteur = recepteur;
		this.address = address;
		this.codePostal = codePostal;
		this.ville = ville;
		this.pays = pays;
		this.telephone = telephone;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "idAddress", column = @Column(name = "id_address", nullable = false)),
			@AttributeOverride(name = "idClient", column = @Column(name = "id_client", nullable = false)) })
	public ClientAddressId getId() {
		return this.id;
	}

	public void setId(ClientAddressId id) {
		this.id = id;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_client", nullable = false, insertable = false, updatable = false)
	public Client getClient() {
		return this.client;
	}

	public void setClient(Client client) {
		this.client = client;
	}

	@Column(name = "recepteur", nullable = false, length = 50)
	public String getRecepteur() {
		return this.recepteur;
	}

	public void setRecepteur(String recepteur) {
		this.recepteur = recepteur;
	}

	@Column(name = "address", nullable = false)
	public String getAddress() {
		return this.address;
	}

	public void setAddress(String address) {
		this.address = address;
	}

	@Column(name = "code_postal", nullable = false, length = 50)
	public String getCodePostal() {
		return this.codePostal;
	}

	public void setCodePostal(String codePostal) {
		this.codePostal = codePostal;
	}

	@Column(name = "ville", nullable = false, length = 50)
	public String getVille() {
		return this.ville;
	}

	public void setVille(String ville) {
		this.ville = ville;
	}

	@Column(name = "pays", nullable = false, length = 50)
	public String getPays() {
		return this.pays;
	}

	public void setPays(String pays) {
		this.pays = pays;
	}

	@Column(name = "telephone", nullable = false, length = 100)
	public String getTelephone() {
		return this.telephone;
	}

	public void setTelephone(String telephone) {
		this.telephone = telephone;
	}

}
