package hibernate_beans;
// Generated 2017-4-28 5:44:07 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Client generated by hbm2java
 */
@Entity
@Table(name = "client", uniqueConstraints = @UniqueConstraint(columnNames = "username"))
public class Client implements java.io.Serializable {

	private int idClient;
	private String username;
	private String password;
	private String nom;
	private String prenom;
	private String gender;
	private Date dateNaissance;
	private Set<ClientAddress> clientAddresses = new HashSet<ClientAddress>(0);

	public Client() {
	}

	public Client(int idClient, String username, String password) {
		this.idClient = idClient;
		this.username = username;
		this.password = password;
	}

	public Client(int idClient, String username, String password, String nom, String prenom, String gender,
			Date dateNaissance, Set<ClientAddress> clientAddresses) {
		this.idClient = idClient;
		this.username = username;
		this.password = password;
		this.nom = nom;
		this.prenom = prenom;
		this.gender = gender;
		this.dateNaissance = dateNaissance;
		this.clientAddresses = clientAddresses;
	}

	@Id

	@Column(name = "id_client", unique = true, nullable = false)
	public int getIdClient() {
		return this.idClient;
	}

	public void setIdClient(int idClient) {
		this.idClient = idClient;
	}

	@Column(name = "username", unique = true, nullable = false, length = 100)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 100)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "nom", length = 100)
	public String getNom() {
		return this.nom;
	}

	public void setNom(String nom) {
		this.nom = nom;
	}

	@Column(name = "prenom", length = 100)
	public String getPrenom() {
		return this.prenom;
	}

	public void setPrenom(String prenom) {
		this.prenom = prenom;
	}

	@Column(name = "gender", length = 2)
	public String getGender() {
		return this.gender;
	}

	public void setGender(String gender) {
		this.gender = gender;
	}

	@Temporal(TemporalType.DATE)
	@Column(name = "date_naissance", length = 10)
	public Date getDateNaissance() {
		return this.dateNaissance;
	}

	public void setDateNaissance(Date dateNaissance) {
		this.dateNaissance = dateNaissance;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "client")
	public Set<ClientAddress> getClientAddresses() {
		return this.clientAddresses;
	}

	public void setClientAddresses(Set<ClientAddress> clientAddresses) {
		this.clientAddresses = clientAddresses;
	}

}
