package hibernate_beans;
// Generated 2017-4-28 5:44:07 by Hibernate Tools 5.2.1.Final

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Jeux generated by hbm2java
 */
@Entity
@Table(name = "jeux")
public class Jeux implements java.io.Serializable {

	private int idJeux;
	private Createur createur;
	private String titre;
	private String photoJeux;
	private String typeConsole;
	private float tarif;
	private int nombreLibre;
	private String descriptionJeux;
	private String typeLivraison;
	private Boolean AVendre;
	private Date datePublication;

	public Jeux() {
	}

	public Jeux(int idJeux, String titre, String typeConsole, float tarif, int nombreLibre, String descriptionJeux,
			String typeLivraison, Date datePublication) {
		this.idJeux = idJeux;
		this.titre = titre;
		this.typeConsole = typeConsole;
		this.tarif = tarif;
		this.nombreLibre = nombreLibre;
		this.descriptionJeux = descriptionJeux;
		this.typeLivraison = typeLivraison;
		this.datePublication = datePublication;
	}

	public Jeux(int idJeux, Createur createur, String titre, String photoJeux, String typeConsole, float tarif,
			int nombreLibre, String descriptionJeux, String typeLivraison, Boolean AVendre, Date datePublication) {
		this.idJeux = idJeux;
		this.createur = createur;
		this.titre = titre;
		this.photoJeux = photoJeux;
		this.typeConsole = typeConsole;
		this.tarif = tarif;
		this.nombreLibre = nombreLibre;
		this.descriptionJeux = descriptionJeux;
		this.typeLivraison = typeLivraison;
		this.AVendre = AVendre;
		this.datePublication = datePublication;
	}

	@Id

	@Column(name = "id_jeux", unique = true, nullable = false)
	public int getIdJeux() {
		return this.idJeux;
	}

	public void setIdJeux(int idJeux) {
		this.idJeux = idJeux;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "id_createur")
	public Createur getCreateur() {
		return this.createur;
	}

	public void setCreateur(Createur createur) {
		this.createur = createur;
	}

	@Column(name = "titre", nullable = false, length = 50)
	public String getTitre() {
		return this.titre;
	}

	public void setTitre(String titre) {
		this.titre = titre;
	}

	@Column(name = "photo_jeux")
	public String getPhotoJeux() {
		return this.photoJeux;
	}

	public void setPhotoJeux(String photoJeux) {
		this.photoJeux = photoJeux;
	}

	@Column(name = "type_console", nullable = false, length = 4)
	public String getTypeConsole() {
		return this.typeConsole;
	}

	public void setTypeConsole(String typeConsole) {
		this.typeConsole = typeConsole;
	}

	@Column(name = "tarif", nullable = false, precision = 12, scale = 0)
	public float getTarif() {
		return this.tarif;
	}

	public void setTarif(float tarif) {
		this.tarif = tarif;
	}

	@Column(name = "nombre_libre", nullable = false)
	public int getNombreLibre() {
		return this.nombreLibre;
	}

	public void setNombreLibre(int nombreLibre) {
		this.nombreLibre = nombreLibre;
	}

	@Column(name = "description_jeux", nullable = false, length = 1000)
	public String getDescriptionJeux() {
		return this.descriptionJeux;
	}

	public void setDescriptionJeux(String descriptionJeux) {
		this.descriptionJeux = descriptionJeux;
	}

	@Column(name = "type_livraison", nullable = false, length = 9)
	public String getTypeLivraison() {
		return this.typeLivraison;
	}

	public void setTypeLivraison(String typeLivraison) {
		this.typeLivraison = typeLivraison;
	}

	@Column(name = "a_vendre")
	public Boolean getAVendre() {
		return this.AVendre;
	}

	public void setAVendre(Boolean AVendre) {
		this.AVendre = AVendre;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "date_publication", nullable = false, length = 19)
	public Date getDatePublication() {
		return this.datePublication;
	}

	public void setDatePublication(Date datePublication) {
		this.datePublication = datePublication;
	}

}
